'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")>  _
Partial Friend NotInheritable Class DefaultValue
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As DefaultValue = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DefaultValue()),DefaultValue)
    
    Public Shared ReadOnly Property [Default]() As DefaultValue
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property PlayerLevel_Min() As Integer
        Get
            Return CType(Me("PlayerLevel_Min"),Integer)
        End Get
        Set
            Me("PlayerLevel_Min") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
    Public Property PlayerLevel_Max() As Integer
        Get
            Return CType(Me("PlayerLevel_Max"),Integer)
        End Get
        Set
            Me("PlayerLevel_Max") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
    Public Property Lv1_Champion_Max() As Integer
        Get
            Return CType(Me("Lv1_Champion_Max"),Integer)
        End Get
        Set
            Me("Lv1_Champion_Max") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
    Public Property Lv2_Champion_Max() As Integer
        Get
            Return CType(Me("Lv2_Champion_Max"),Integer)
        End Get
        Set
            Me("Lv2_Champion_Max") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
    Public Property Lv3_Champion_Max() As Integer
        Get
            Return CType(Me("Lv3_Champion_Max"),Integer)
        End Get
        Set
            Me("Lv3_Champion_Max") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
    Public Property Lv4_Champion_Max() As Integer
        Get
            Return CType(Me("Lv4_Champion_Max"),Integer)
        End Get
        Set
            Me("Lv4_Champion_Max") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
    Public Property Lv5_Champion_Max() As Integer
        Get
            Return CType(Me("Lv5_Champion_Max"),Integer)
        End Get
        Set
            Me("Lv5_Champion_Max") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
    Public Property ChampionLevel_Max() As Integer
        Get
            Return CType(Me("ChampionLevel_Max"),Integer)
        End Get
        Set
            Me("ChampionLevel_Max") = value
        End Set
    End Property
End Class
